version: "3.10"

services:
  db:
    container_name: "jukebox_db"
    image: postgres:13.4
    volumes:
      - .pgdata:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "jukebox_db"

  db_test:
    container_name: "jukebox_db_test"
    image: postgres:13.4
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "jukebox_db_test"
